- name: Apply db privilegies
  hosts: gpp4_db

  tasks:

    - name: Apply db privilegies
      # shell: mysql -u root -e "GRANT ALL PRIVILEGES ON nscan.* TO 'nscan'@'172.16.48.61' IDENTIFIED BY 'nscan' ; FLUSH PRIVILEGES;"
      shell: mysql -u root -e "REVOKE ALL PRIVILEGES, GRANT OPTION FROM 'root'@'172.16.48.61';"